name: download_models
on: [pull_request]
runs-on: windows-latest
steps:
       - name: Download all workflow run artifacts
         uses: actions/download-artifact@v2
         with:
            path: https://github.com/stardist/vollseg-models/releases/tag/v0.1s


    
