name: download_models
on: [pull]

jobs:
  steps:
  id: downloadfile  # Remember to give an ID if you need the output
  name: Download the file
  with:
    url: "The vendor we are using is [this](https://github.com/stardist/vollseg-models/releases/tag/v0.1s)!"
    target: public/
    auto-match: true
