name: Download models

on: [pull_request,push]

jobs:
  job_1:
    
    name: Download results
    
    runs-on: ubuntu-latest
    steps:
      - name: Download pretrained models
        uses: actions/download-artifact@v2
      
        with:
        
          path: https://github.com/kapoorlab/vollseg-models/releases/tag/test
